FROM mhart/alpine-node:11.1.0

RUN mkdir /web-app

WORKDIR /web-app

RUN apk update && apk upgrade && apk add --no-cache git

COPY package.json /web-app/package.json

RUN yarn install

COPY . /web-app/

RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
